name: build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B out/build/ci -A x64 -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build out/build/ci --config Debug --parallel

      - name: Test
        run: ctest --test-dir out/build/ci -C Debug --output-on-failure

